### ISSUE TITLE
two withdraw msg were included in one tx

### ISSUE THREAD

**Issue by bradyjoestar** [mantlenetworkio/mantle#315]
https://explorer.testnet.mantlenetwork.io/tx/0xaa75e43b2b0d210dfbc1a9ff994322709286e6e3ab813cc11dbac8436e1e434f
![2022-11-21 20-27-57屏幕截图](https://user-images.githubusercontent.com/29145722/203055416-76214082-1f49-4403-b15c-b82d3150a731.png)

which caused the `claim` failed. 

Error log:
```
Error: expected 1 message, got 2
      at CrossChainMessenger.toCrossChainMessage (node_modules/@mantleio/sdk/src/cross-chain-messenger.ts:369:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.finalizeMessage (node_modules/@mantleio/sdk/src/cross-chain-messenger.ts:1085:24)
      at async CrossChainMessenger.finalizeMessage (node_modules/@mantleio/sdk/src/cross-chain-messenger.ts:925:7)
      at async Context.<anonymous> (test/d&w_ETH.ts:278:39)
```

**Comment by wukongcheng** [comment]
The tx of burning L2 gas fee is triggered automaticly as a withdraw tx with a user's tx.  @curryxbo will update the burning mechanism.

**Comment by wukongcheng** [comment]
https://github.com/mantlenetworkio/mantle/pull/323
