### ISSUE TITLE
ops integration-tests build error

### ISSUE THREAD

**Issue by aodhgan** [mantlenetworkio/mantle#514]
For a fresh build, on MacOS, following the build instructions, running `cd ops/ && docker-compose build` is giving:

```
 => [base 19/20] COPY ./integration-tests ./integration-tests                                                                                                                                0.7s
 => ERROR [base 20/20] RUN yarn build                                                                                                                                                        8.7s
------
 > [base 20/20] RUN yarn build:
#26 0.284 yarn run v1.22.19
#26 0.313 $ yarn lerna run build
#26 0.451 $ /opt/mantle/node_modules/.bin/lerna run build
#26 0.781 lerna notice cli v4.0.0
#26 0.783 lerna info versioning independent
#26 0.820 lerna info Executing command in 10 packages: "yarn run build"
#26 2.289 lerna info run Ran npm script 'build' in '@mantleio/core-utils' in 1.5s:
#26 2.289 $ tsc -p tsconfig.json
#26 3.012 $ tsc -p tsconfig.json
#26 3.012 lerna info run Ran npm script 'build' in '@mantleio/hardhat-deploy-config' in 2.2s:
#26 4.957 lerna info run Ran npm script 'build' in '@mantleio/common-ts' in 2.7s:
#26 4.957 $ tsc -p tsconfig.json
#26 5.032 lerna info run Ran npm script 'build' in '@mantleio/sdk' in 2.7s:
#26 5.032 $ tsc -p tsconfig.json
#26 8.309 lerna$ tsc -p tsconfig.json
#26 8.309  info run Ran npm script 'build' in '@mantleio/replica-healthcheck' in 3.3s:
#26 8.422 lerna ERR! yarn run build exited 1 in '@mantleio/integration-tests'
#26 8.422 lerna ERR! yarn run build stdout:
#26 8.422 $ hardhat compile
#26 8.422 Downloading compiler 0.8.9
#26 8.422 
#26 8.422 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#26 8.422 lerna ERR! yarn run build stderr:
#26 8.422 An unexpected error occurred:
#26 8.422 SyntaxError: /root/.cache/hardhat-nodejs/compilers/linux-amd64/list.json: Unexpected end of JSON input
#26 8.422     at JSON.parse (<anonymous>)
#26 8.422     at /opt/mantle/node_modules/jsonfile/index.js:33:18
#26 8.422     at /opt/mantle/node_modules/graceful-fs/graceful-fs.js:123:16
#26 8.422     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
#26 8.422 error Command failed with exit code 1.
#26 8.422 lerna ERR! yarn run build exited 1 in '@mantleio/integration-tests'
#26 8.422 lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
#26 8.457 error Command failed with exit code 1.
#26 8.457 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#26 8.550 error Command failed with exit code 1.
#26 8.552 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build]: exit code: 1
ERROR: Service 'deployer' failed to build : Build failed
```

**Comment by aodhgan** [comment]
which intermittently also gives:

```
#26 16.14 lerna ERR! yarn run build exited 1 in '@mantleio/contracts'
#26 16.14 lerna ERR! yarn run build stdout:
#26 16.14 $ yarn build:contracts && yarn autogen:artifacts && yarn build:typescript
#26 16.14 $ hardhat compile --show-stack-traces
#26 16.14 running task
#26 16.14 end task
#26 16.14 Downloading compiler 0.8.9
#26 16.14 Downloading compiler 0.5.17
#26 16.14 
#26 16.14 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#26 16.14 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#26 16.14 lerna ERR! yarn run build stderr:
#26 16.14 Error HH501: Couldn't download compiler version 0.8.9+commit.e5eed63a. Please check your internet connection and try again.
#26 16.14 HardhatError: HH501: Couldn't download compiler version 0.8.9+commit.e5eed63a. Please check your internet connection and try again.
```

It seems like hardhat can't download/find/access the solc compilers at `/root/.cache/hardhat-nodejs/compilers/linux-amd64/tmp-solc-linux-amd64-v0.8.9+commit.e5eed63a` perhaps they need to be copied into the container first
